workflows:
  version: 2
  test_build_release:
    jobs:
      test:
        working_directory: /go/src/github.com/regner/albionmarket-client
        docker:
          - image: circleci/golang:1.8
        steps:
          - checkout
          - run: go get golang.org/x/tools/cmd/goimports
          - run: make validate-fmt
      build_windows:
        requires:
          - test
        working_directory: /go/src/github.com/regner/albionmarket-client
        docker:
          - image: circleci/golang:1.8
        steps:
          - checkout
          - run: apt-get install -y build-essential mingw-w64
          - run: make build-windows
